apiVersion: apps/v1
kind: Deployment
metadata:
  name: barnacle-reviews
template:
  metadata:
    labels:
      app: barnacle-reviews
  spec:
    containers:
      - name: barnacle-reviews
        image: barnacle-reviews:latest
        ports:
          - containerPort: 8080
        env:
          - name: DATABASE_URL
            value: "postgres://user:password@postgresql:5432/dbname?sslmode=disable"
---
apiVersion: v1
kind: Service
metadata:
  name: barnacle-reviews
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: barnacle-reviews