apiVersion: automation.cloudbees.io/v1alpha1
kind: Workflow
name: Urchin Analytics Kaniko Build and Deploy
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
env:
  CONTAINER_DEST: cb-squidstack/urchin-analytics:${{ cloudbees.version }},cb-squidstack/urchin-analytics:latest
jobs:
  build:
    steps:
      - uses: docker://alpine/git:2.43.0
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Setup Docker Hub Registry
        with:
          registry: index.docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build a container image with Kaniko
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: ${{ env.CONTAINER_DEST }}
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=CloudBees CI,"version=${{ cloudbees.version }}"
  manage_chart:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
        shell: sh
      - uses: docker://alpine/helm:3.14.2
        name: package
        run: |
          pwd
          ls -lart
          cd chart
          helm package urchin --version ${{ cloudbees.version }} --app-version ${{ cloudbees.version }}
          ls -lart
        shell: sh
      - uses: actions/helm-push@1.6
        name: publish
        with:
          chart_package: chart/urchin-${{ cloudbees.version }}.tgz
          remote_repo: $NEXUS_REPO
          remote_user_name: ${{ vars.NEXUS_USERNAME }}
          remote_password: ${{ secrets.NEXUS_PASSWORD }}
  deploy_dev:
    environment: dev_env
    steps:
      - uses: argocd-actions/argocd-create-update-project@0.25
        name: deploy_argocd
        with:
          serverurl: ${{ vars.argocd_url }}
          user: ${{ vars.argocd_user }}
          credential: ${{ secrets.argocd_cred }}
          projectname: default
          projectdescription: created via the cloudbees platform
          applicationname: urchin-dev
          repourl: $NEXUS_REPO
          targetrevision: ${{ cloudbees.version }}
          destnamespace: urchin-dev
          chartname: urchin
          deploytype: helm
    needs:
      - build
      - manage_chart
  deploy_preprod:
    environment: preprod_env
    steps:
      - uses: argocd-actions/argocd-create-update-project@0.25
        name: deploy_argocd
        with:
          serverurl: ${{ vars.argocd_url }}
          user: ${{ vars.argocd_user }}
          credential: ${{ secrets.argocd_cred }}
          projectname: default
          projectdescription: created via the cloudbees platform
          applicationname: urchin-preprod
          repourl: $NEXUS_REPO
          targetrevision: ${{ cloudbees.version }}
          destnamespace: urchin-preprod
          chartname: urchin
          deploytype: helm
    needs:
      - deploy_dev
  deploy_prod:
    environment: prod_env
    steps:
      - uses: argocd-actions/argocd-create-update-project@0.25
        name: deploy_argocd
        with:
          serverurl: ${{ vars.argocd_url }}
          user: ${{ vars.argocd_user }}
          credential: ${{ secrets.argocd_cred }}
          projectname: default
          projectdescription: created via the cloudbees platform
          applicationname: urchin-prod
          repourl: $NEXUS_REPO
          targetrevision: ${{ cloudbees.version }}
          destnamespace: urchin-prod
          chartname: urchin
          deploytype: helm
    needs:
      - deploy_preprod