apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: squid-ui
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: squid-ui
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.ingress.hostName }}
      secretName: squid-ui-tls